# Generated by Django 4.1.1 on 2024-08-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_content'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='search_index',
        ),
    ]
